{% set name = "paramspace" %}
{% set version = "2.5.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: abda353e92cdc136ff7be1cb95fe320a5d4f982df35cb5ddde1d53cc5b3aaec3

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - numpy >=1.17.3
    - ruamel.yaml >=0.16.5
    - xarray >=0.10.9
  run:
    - python
    - numpy >=1.17.3
    - ruamel.yaml >=0.16.5
    - xarray >=0.10.9

test:
  imports:
    - paramspace
  requires:
    - pytest >=3.4
    - pytest-cov >=2.6
  # commands:
  #   - "{{ PYTHON }} -m pytest -v tests/ --cov=paramspace --cov-report=term-missing"

about:
  home: "https://ts-gitlab.iup.uni-heidelberg.de/yunus/paramspace"
  license: BSD
  license_family: BSD
  license_file: 
  summary: "Dictionary-based, multi-dimensional parameter space iteration"
  doc_url: "https://paramspace.readthedocs.io/en/latest/"
  dev_url: "https://ts-gitlab.iup.uni-heidelberg.de/yunus/paramspace"

extra:
  recipe-maintainers:
    - blsqr
